#!/usr/bin/env python
# -*- coding: utf-8 -*-

import cmd
import os
from os.path import join as join_path, dirname
import sqlite3
import sys


def data_file(fn):
    return join_path(dirname(__file__), 'data', fn)

DB_SCRIPT = open(data_file('capo.ddl')).read()


class CapoCmd(object, cmd.Cmd):
    intro = """
	capo - your friendly handicap-race manager
	""".strip()

    def __init__(self, dbconn):
        cmd.Cmd.__init__(self)
        self._db = dbconn

    def do_quit(self, line):
        """Stop Capo."""
        print line
        return True

    do_exit = do_quit

    def do_runners(self, line):
        """
        Print out all known runners
        """
        runners = self._db.execute("""SELECT person.name AS name FROM person""")
        for runner in runners:
            print runner[0]


    def do_testdata(self, line):
        """ Load test data into the database
        """
        test_script = open(data_file('testdata.sql')).read()
        self._db.executescript(test_script)



def main(argv=sys.argv[1:]):
	new_db = not os.path.exists('capo.sqlite')

	dbconn = sqlite3.connect('capo.sqlite')
	if new_db:
		dbconn.executescript(DB_SCRIPT)

	driver = CapoCmd(dbconn)
	driver.cmdloop()


if __name__ == '__main__':
	main()